### ISSUE TITLE
CI build is running in both of travis-ci.com and .org

### ISSUE THREAD

**Issue by KengoTODA** [WorksApplications/kintoki#5]
Travis has two domains: travis-ci.com and travis-ci.org. And now we run our build in both sites, see #4 as example.

Travis CI has [decided to merge travis-ci.org to travis-ci.com (a.k.a. Travis pro)](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) so it's better to stop the build on .org site, I think.

We can disable builds at [this configuration page](https://travis-ci.org/WorksApplications/kintoki/settings).

**Comment by kazuma-t** [comment]
I've changed the settings to build at travis-ci.com and disable builds at travis-ci.org.
Thank you.
